# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OuiCodeData
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A website about spatial data, artificial intelligence and data science
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ouicodegis
github_username:  paulofpimenta
disqus_username:

# Build settings
markdown: kramdown
#permalink: /:categories/:title/

# Gems settings
plugins:
  - jekyll-scholar
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate

# Jekyl SEO Tag setup
twitter:
  username: ouicodegis
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://twitter.com/ouicodegis
    - https://github.com/paulofpimenta
google_site_verification: xxxxx
lang: en

# Jekyl Scholar setup
scholar:
  style: _bibliography/simple-ieee.csl
  bibliography: references.bib

  sort_by: year
  order: ascending

  details_dir:    bibliography
  bibliography_template: bib
  details_layout: bibtex.html
  details_link:   Details
  replace_strings: true
  query: "@*"

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  style: compressed


images: '/assets/images'


# Outputting
############################################################
paginate: 5
permalink: /posts/:title/
paginate_path: /page:num
# Set the time zone for site generation.
timezone: Europe/Paris

