# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OuiCodeData
email: pfpimenta@gmail.com
description: # this means to ignore newlines until "baseurl:"
  A portal with news, tutorials and tips about GIS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paulofpimenta.github.io/ouicodedata/" # the base hostname & protocol for your site
github_username:  paulofpimenta
twitter_username:  paulofpimenta
linkedin_username:  paulofpimenta

permalink: none

# Gems settings
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  #- jekyll-redirect-from

# Where things are
############################################################
#source: . # Set by GitHub
# This is where the generated site will be placed once Jekyll is done transforming it.
destination: ./_site#
#plugins_dir: ./_plugins
# This folder is for the main templates your content will be inserted into. You can have different layouts for different pages or page sections.
#layouts_dir: ./_layouts
#data_dir: ./_data
#collections: null

# Add portfolio folder




# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Paulo Pimenta"


#Plugins
############################################################

#Carousel configuration
#iis_slider_array: []



# Outputting
############################################################
permalink: /posts/:title/
paginate_path: /page:num
# Set the time zone for site generation.
timezone: Europe/Paris